// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpnGvOoqOzjycMnXZA5WkMHYqO1QadtZY',
    appId: '1:982718824185:web:9ef228cd31642d25136c28',
    messagingSenderId: '982718824185',
    projectId: 'connectv01pamodzi',
    authDomain: 'connectv01pamodzi.firebaseapp.com',
    storageBucket: 'connectv01pamodzi.appspot.com',
    measurementId: 'G-12WGFDERLV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDq9PutoDxiJ7Q2dp10Pztnj9u9b6ZSeLM',
    appId: '1:982718824185:android:c971da8b1d12a563136c28',
    messagingSenderId: '982718824185',
    projectId: 'connectv01pamodzi',
    storageBucket: 'connectv01pamodzi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNZ5b9SNmHxEIkVKHZfXub_xb4gkYODHE',
    appId: '1:982718824185:ios:fb8ca4f678e25f19136c28',
    messagingSenderId: '982718824185',
    projectId: 'connectv01pamodzi',
    storageBucket: 'connectv01pamodzi.appspot.com',
    iosClientId: '982718824185-kedqml2kptago60t6pib6ohh31pjpssm.apps.googleusercontent.com',
    iosBundleId: 'com.example.connectv01pamodzi',
  );
}
